namespace MCBp.Localization;

/// <summary>
/// Менеджер локализации на 10 языков.
/// </summary>
public static class LocalizationManager
{
    public static Language CurrentLanguage { get; set; } = Language.Russian;

    public static event Action? LanguageChanged;

    public static void SetLanguage(Language lang)
    {
        CurrentLanguage = lang;
        LanguageChanged?.Invoke();
    }

    public static string GetNativeName(Language lang) => lang switch
    {
        Language.English => "English",
        Language.Russian => "Русский",
        Language.Spanish => "Español",
        Language.German => "Deutsch",
        Language.French => "Français",
        Language.Chinese => "简体中文",
        Language.Japanese => "日本語",
        Language.Portuguese => "Português",
        Language.Italian => "Italiano",
        Language.Korean => "한국어",
        _ => "English"
    };

    public static string Get(string key)
    {
        if (_translations.TryGetValue(CurrentLanguage, out var map) && map.TryGetValue(key, out var val))
            return val;

        if (_translations[Language.English].TryGetValue(key, out var fallback))
            return fallback;

        return key;
    }

    private static readonly Dictionary<Language, Dictionary<string, string>> _translations = new()
    {
        [Language.English] = new()
        {
            ["AppTitle"] = "MCBlueprint — Minecraft architect tool",
            ["NewProjectTitle"] = "MCBlueprint — New Project",
            ["MenuFile"] = "File",
            ["MenuNew"] = "New Project",
            ["MenuOpen"] = "Open...",
            ["MenuSave"] = "Save",
            ["MenuSaveAs"] = "Save As...",
            ["MenuExit"] = "Exit",
            ["MenuEdit"] = "Edit",
            ["MenuUndo"] = "Undo",
            ["MenuRedo"] = "Redo",
            ["MenuClearAll"] = "Clear All",
            ["MenuView"] = "View",
            ["MenuGrid"] = "Grid",
            ["MenuCenterCamera"] = "Center Camera",
            ["MenuLanguage"] = "Language",
            ["MenuHelp"] = "Help",
            ["MenuAbout"] = "About",
            ["ToolPointer"] = "Pointer / Move text [0]",
            ["ToolBrush"] = "Brush [1]",
            ["ToolLine"] = "Line [2]",
            ["ToolRectangle"] = "Rectangle [3]",
            ["ToolCircle"] = "Circle [4]",
            ["ToolArc"] = "Arc (pull curve pixel) [5]",
            ["ToolText"] = "Text [6]",
            ["ToolRuler"] = "Ruler [7]",
            ["ToolEraser"] = "Eraser [8]",
            ["ToolColor"] = "Select Block/Text Color",
            ["ToolFont"] = "Select Font",
            ["ToolUndo"] = "Undo (Ctrl+Z)",
            ["ToolRedo"] = "Redo (Ctrl+X / Ctrl+Y)",
            ["ToolGrid"] = "Toggle Grid (G)",
            ["StatusSize"] = "Size",
            ["StatusBlocks"] = "Blocks",
            ["StatusZoom"] = "Zoom",
            ["AboutTitle"] = "About MCBlueprint",
            ["AboutText"] = "MCBlueprint — Minecraft Architect & Planner Tool\n\nInfinite 2D canvas for blueprint design.\n\nShortcuts:\n0-8: Select Tool\nCtrl+Z: Undo\nCtrl+X / Ctrl+Y: Redo\nG: Toggle Grid\nRMB/MMB: Pan\nWheel: Zoom",
            ["BlocksLabel"] = "bl."
        },
        [Language.Russian] = new()
        {
            ["AppTitle"] = "MCBlueprint — Архитектор Minecraft",
            ["NewProjectTitle"] = "MCBp — Новый проект",
            ["MenuFile"] = "Файл",
            ["MenuNew"] = "Новый проект",
            ["MenuOpen"] = "Открыть...",
            ["MenuSave"] = "Сохранить",
            ["MenuSaveAs"] = "Сохранить как...",
            ["MenuExit"] = "Выход",
            ["MenuEdit"] = "Правка",
            ["MenuUndo"] = "Отменить",
            ["MenuRedo"] = "Повторить",
            ["MenuClearAll"] = "Очистить всё",
            ["MenuView"] = "Вид",
            ["MenuGrid"] = "Сетка",
            ["MenuCenterCamera"] = "Центрировать камеру",
            ["MenuLanguage"] = "Язык",
            ["MenuHelp"] = "Справка",
            ["MenuAbout"] = "О программе",
            ["ToolPointer"] = "Указатель / Перемещение текста [0]",
            ["ToolBrush"] = "Кисть [1]",
            ["ToolLine"] = "Линия [2]",
            ["ToolRectangle"] = "Прямоугольник [3]",
            ["ToolCircle"] = "Круг [4]",
            ["ToolArc"] = "Дуга (управление изгибом за пиксель) [5]",
            ["ToolText"] = "Текст [6]",
            ["ToolRuler"] = "Линейка [7]",
            ["ToolEraser"] = "Ластик [8]",
            ["ToolColor"] = "Выбор цвета блока/текста",
            ["ToolFont"] = "Выбор шрифта текста",
            ["ToolUndo"] = "Отменить (Ctrl+Z)",
            ["ToolRedo"] = "Повторить (Ctrl+X / Ctrl+Y)",
            ["ToolGrid"] = "Показать/скрыть сетку (G)",
            ["StatusSize"] = "Размер",
            ["StatusBlocks"] = "Блоков",
            ["StatusZoom"] = "Масштаб",
            ["AboutTitle"] = "О программе MCBp",
            ["AboutText"] = "MCBp — Планировщик и архитектор построек Minecraft\n\nБесконечный 2D-холст для разметки.\n\nГорячие клавиши:\n0-8: Выбор инструмента\nCtrl+Z: Отменить\nCtrl+X / Ctrl+Y: Повторить\nG: Сетка\nПКМ/СКМ: Панорамирование\nКолёсико: Масштабирование",
            ["BlocksLabel"] = "бл."
        },
        [Language.Spanish] = new()
        {
            ["AppTitle"] = "MCBlueprint — Herramienta de arquitectura para Minecraft",
            ["NewProjectTitle"] = "MCBlueprint — Nuevo Proyecto",
            ["MenuFile"] = "Archivo",
            ["MenuNew"] = "Nuevo Proyecto",
            ["MenuOpen"] = "Abrir...",
            ["MenuSave"] = "Guardar",
            ["MenuSaveAs"] = "Guardar como...",
            ["MenuExit"] = "Salir",
            ["MenuEdit"] = "Edición",
            ["MenuUndo"] = "Deshacer",
            ["MenuRedo"] = "Rehacer",
            ["MenuClearAll"] = "Borrar todo",
            ["MenuView"] = "Ver",
            ["MenuGrid"] = "Cuadrícula",
            ["MenuCenterCamera"] = "Centrar cámara",
            ["MenuLanguage"] = "Idioma",
            ["MenuHelp"] = "Ayuda",
            ["MenuAbout"] = "Acerca de",
            ["ToolPointer"] = "Puntero / Mover texto [0]",
            ["ToolBrush"] = "Pincel [1]",
            ["ToolLine"] = "Línea [2]",
            ["ToolRectangle"] = "Rectángulo [3]",
            ["ToolCircle"] = "Círculo [4]",
            ["ToolArc"] = "Arco [5]",
            ["ToolText"] = "Texto [6]",
            ["ToolRuler"] = "Regla [7]",
            ["ToolEraser"] = "Goma de borrar [8]",
            ["ToolColor"] = "Color de bloque/texto",
            ["ToolFont"] = "Fuente",
            ["ToolUndo"] = "Deshacer (Ctrl+Z)",
            ["ToolRedo"] = "Rehacer (Ctrl+X / Ctrl+Y)",
            ["ToolGrid"] = "Alternar cuadrícula (G)",
            ["StatusSize"] = "Tamaño",
            ["StatusBlocks"] = "Bloques",
            ["StatusZoom"] = "Zoom",
            ["AboutTitle"] = "Acerca de MCBlueprint",
            ["AboutText"] = "MCBlueprint — Herramienta de arquitectura para Minecraft",
            ["BlocksLabel"] = "bloq."
        },
        [Language.German] = new()
        {
            ["AppTitle"] = "MCBlueprint — Minecraft Architekten-Werkzeug",
            ["NewProjectTitle"] = "MCBlueprint — Neues Projekt",
            ["MenuFile"] = "Datei",
            ["MenuNew"] = "Neues Projekt",
            ["MenuOpen"] = "Öffnen...",
            ["MenuSave"] = "Speichern",
            ["MenuSaveAs"] = "Speichern unter...",
            ["MenuExit"] = "Beenden",
            ["MenuEdit"] = "Bearbeiten",
            ["MenuUndo"] = "Rückgängig",
            ["MenuRedo"] = "Wiederholen",
            ["MenuClearAll"] = "Alles löschen",
            ["MenuView"] = "Ansicht",
            ["MenuGrid"] = "Raster",
            ["MenuCenterCamera"] = "Kamera zentrieren",
            ["MenuLanguage"] = "Sprache",
            ["MenuHelp"] = "Hilfe",
            ["MenuAbout"] = "Über",
            ["ToolPointer"] = "Zeiger / Text bewegen [0]",
            ["ToolBrush"] = "Pinsel [1]",
            ["ToolLine"] = "Linie [2]",
            ["ToolRectangle"] = "Rechteck [3]",
            ["ToolCircle"] = "Kreis [4]",
            ["ToolArc"] = "Bogen [5]",
            ["ToolText"] = "Text [6]",
            ["ToolRuler"] = "Lineal [7]",
            ["ToolEraser"] = "Radiergummi [8]",
            ["ToolColor"] = "Farbe auswählen",
            ["ToolFont"] = "Schriftart auswählen",
            ["ToolUndo"] = "Rückgängig (Ctrl+Z)",
            ["ToolRedo"] = "Wiederholen (Ctrl+X / Ctrl+Y)",
            ["ToolGrid"] = "Raster umschalten (G)",
            ["StatusSize"] = "Größe",
            ["StatusBlocks"] = "Blöcke",
            ["StatusZoom"] = "Zoom",
            ["AboutTitle"] = "Über MCBlueprint",
            ["AboutText"] = "MCBlueprint — Minecraft Architekten-Werkzeug",
            ["BlocksLabel"] = "Bl."
        },
        [Language.French] = new()
        {
            ["AppTitle"] = "MCBlueprint — Outil d'architecture Minecraft",
            ["NewProjectTitle"] = "MCBlueprint — Nouveau Projet",
            ["MenuFile"] = "Fichier",
            ["MenuNew"] = "Nouveau Projet",
            ["MenuOpen"] = "Ouvrir...",
            ["MenuSave"] = "Enregistrer",
            ["MenuSaveAs"] = "Enregistrer sous...",
            ["MenuExit"] = "Quitter",
            ["MenuEdit"] = "Édition",
            ["MenuUndo"] = "Annuler",
            ["MenuRedo"] = "Rétablir",
            ["MenuClearAll"] = "Tout effacer",
            ["MenuView"] = "Affichage",
            ["MenuGrid"] = "Grille",
            ["MenuCenterCamera"] = "Centrer la caméra",
            ["MenuLanguage"] = "Langue",
            ["MenuHelp"] = "Aide",
            ["MenuAbout"] = "À propos",
            ["ToolPointer"] = "Pointeur / Déplacer texte [0]",
            ["ToolBrush"] = "Pinceau [1]",
            ["ToolLine"] = "Ligne [2]",
            ["ToolRectangle"] = "Rectangle [3]",
            ["ToolCircle"] = "Cercle [4]",
            ["ToolArc"] = "Arc [5]",
            ["ToolText"] = "Texte [6]",
            ["ToolRuler"] = "Règle [7]",
            ["ToolEraser"] = "Gomme [8]",
            ["ToolColor"] = "Couleur",
            ["ToolFont"] = "Police",
            ["ToolUndo"] = "Annuler (Ctrl+Z)",
            ["ToolRedo"] = "Rétablir (Ctrl+X / Ctrl+Y)",
            ["ToolGrid"] = "Activer grille (G)",
            ["StatusSize"] = "Taille",
            ["StatusBlocks"] = "Blocs",
            ["StatusZoom"] = "Zoom",
            ["AboutTitle"] = "À propos de MCBlueprint",
            ["AboutText"] = "MCBlueprint — Outil d'architecture Minecraft",
            ["BlocksLabel"] = "blocs"
        },
        [Language.Chinese] = new()
        {
            ["AppTitle"] = "MCBlueprint — Minecraft 建筑规划工具",
            ["NewProjectTitle"] = "MCBlueprint — 新建项目",
            ["MenuFile"] = "文件",
            ["MenuNew"] = "新建项目",
            ["MenuOpen"] = "打开...",
            ["MenuSave"] = "保存",
            ["MenuSaveAs"] = "另存为...",
            ["MenuExit"] = "退出",
            ["MenuEdit"] = "编辑",
            ["MenuUndo"] = "撤销",
            ["MenuRedo"] = "重做",
            ["MenuClearAll"] = "清空全部",
            ["MenuView"] = "视图",
            ["MenuGrid"] = "网格",
            ["MenuCenterCamera"] = "居中视角",
            ["MenuLanguage"] = "语言",
            ["MenuHelp"] = "帮助",
            ["MenuAbout"] = "关于",
            ["ToolPointer"] = "指针 / 移动文本 [0]",
            ["ToolBrush"] = "画笔 [1]",
            ["ToolLine"] = "直线 [2]",
            ["ToolRectangle"] = "矩形 [3]",
            ["ToolCircle"] = "圆形 [4]",
            ["ToolArc"] = "弧线 [5]",
            ["ToolText"] = "文本 [6]",
            ["ToolRuler"] = "直尺 [7]",
            ["ToolEraser"] = "橡皮擦 [8]",
            ["ToolColor"] = "选择颜色",
            ["ToolFont"] = "选择字体",
            ["ToolUndo"] = "撤销 (Ctrl+Z)",
            ["ToolRedo"] = "重做 (Ctrl+X / Ctrl+Y)",
            ["ToolGrid"] = "切换网格 (G)",
            ["StatusSize"] = "尺寸",
            ["StatusBlocks"] = "方块数",
            ["StatusZoom"] = "缩放",
            ["AboutTitle"] = "关于 MCBlueprint",
            ["AboutText"] = "MCBlueprint — Minecraft 2D 建筑规划工具",
            ["BlocksLabel"] = "方块"
        },
        [Language.Japanese] = new()
        {
            ["AppTitle"] = "MCBlueprint — Minecraft 建築設計ツール",
            ["NewProjectTitle"] = "MCBlueprint — 新規プロジェクト",
            ["MenuFile"] = "ファイル",
            ["MenuNew"] = "新規プロジェクト",
            ["MenuOpen"] = "开く...",
            ["MenuSave"] = "保存",
            ["MenuSaveAs"] = "名前を付けて保存...",
            ["MenuExit"] = "終了",
            ["MenuEdit"] = "編集",
            ["MenuUndo"] = "元に戻す",
            ["MenuRedo"] = "やり直す",
            ["MenuClearAll"] = "すべてクリア",
            ["MenuView"] = "表示",
            ["MenuGrid"] = "グリッド",
            ["MenuCenterCamera"] = "カメラを中心に配置",
            ["MenuLanguage"] = "言語",
            ["MenuHelp"] = "ヘルプ",
            ["MenuAbout"] = "バージョン情報",
            ["ToolPointer"] = "ポインター / テキスト移動 [0]",
            ["ToolBrush"] = "ブラシ [1]",
            ["ToolLine"] = "直線 [2]",
            ["ToolRectangle"] = "長方形 [3]",
            ["ToolCircle"] = "円 [4]",
            ["ToolArc"] = "弧 [5]",
            ["ToolText"] = "テキスト [6]",
            ["ToolRuler"] = "定規 [7]",
            ["ToolEraser"] = "消しゴム [8]",
            ["ToolColor"] = "色を選択",
            ["ToolFont"] = "フォントを選択",
            ["ToolUndo"] = "元に戻す (Ctrl+Z)",
            ["ToolRedo"] = "やり直す (Ctrl+X / Ctrl+Y)",
            ["ToolGrid"] = "グリッド切り替え (G)",
            ["StatusSize"] = "サイズ",
            ["StatusBlocks"] = "ブロック数",
            ["StatusZoom"] = "ズーム",
            ["AboutTitle"] = "MCBlueprint について",
            ["AboutText"] = "MCBlueprint — Minecraft 建築設計ツール",
            ["BlocksLabel"] = "個"
        },
        [Language.Portuguese] = new()
        {
            ["AppTitle"] = "MCBlueprint — Ferramenta de Arquitetura para Minecraft",
            ["NewProjectTitle"] = "MCBlueprint — Novo Projeto",
            ["MenuFile"] = "Arquivo",
            ["MenuNew"] = "Novo Projeto",
            ["MenuOpen"] = "Abrir...",
            ["MenuSave"] = "Salvar",
            ["MenuSaveAs"] = "Salvar como...",
            ["MenuExit"] = "Sair",
            ["MenuEdit"] = "Editar",
            ["MenuUndo"] = "Desfazer",
            ["MenuRedo"] = "Refazer",
            ["MenuClearAll"] = "Limpar tudo",
            ["MenuView"] = "Exibir",
            ["MenuGrid"] = "Grade",
            ["MenuCenterCamera"] = "Centralizar Câmera",
            ["MenuLanguage"] = "Idioma",
            ["MenuHelp"] = "Ajuda",
            ["MenuAbout"] = "Sobre",
            ["ToolPointer"] = "Ponteiro / Mover texto [0]",
            ["ToolBrush"] = "Pincel [1]",
            ["ToolLine"] = "Linha [2]",
            ["ToolRectangle"] = "Retângulo [3]",
            ["ToolCircle"] = "Círculo [4]",
            ["ToolArc"] = "Arco [5]",
            ["ToolText"] = "Texto [6]",
            ["ToolRuler"] = "Régua [7]",
            ["ToolEraser"] = "Borracha [8]",
            ["ToolColor"] = "Selecionar Cor",
            ["ToolFont"] = "Selecionar Fonte",
            ["ToolUndo"] = "Desfazer (Ctrl+Z)",
            ["ToolRedo"] = "Refazer (Ctrl+X / Ctrl+Y)",
            ["ToolGrid"] = "Alternar Grade (G)",
            ["StatusSize"] = "Tamanho",
            ["StatusBlocks"] = "Blocos",
            ["StatusZoom"] = "Zoom",
            ["AboutTitle"] = "Sobre o MCBlueprint",
            ["AboutText"] = "MCBlueprint — Ferramenta de Arquitetura para Minecraft",
            ["BlocksLabel"] = "bl."
        },
        [Language.Italian] = new()
        {
            ["AppTitle"] = "MCBlueprint — Strumento di architettura per Minecraft",
            ["NewProjectTitle"] = "MCBlueprint — Nuovo Progetto",
            ["MenuFile"] = "File",
            ["MenuNew"] = "Nuovo Progetto",
            ["MenuOpen"] = "Apri...",
            ["MenuSave"] = "Salva",
            ["MenuSaveAs"] = "Salva con nome...",
            ["MenuExit"] = "Esci",
            ["MenuEdit"] = "Modifica",
            ["MenuUndo"] = "Annulla",
            ["MenuRedo"] = "Ripristina",
            ["MenuClearAll"] = "Cancella tutto",
            ["MenuView"] = "Visualizza",
            ["MenuGrid"] = "Griglia",
            ["MenuCenterCamera"] = "Centra fotocamera",
            ["MenuLanguage"] = "Lingua",
            ["MenuHelp"] = "Aiuto",
            ["MenuAbout"] = "Informazioni",
            ["ToolPointer"] = "Puntatore / Sposta testo [0]",
            ["ToolBrush"] = "Pennello [1]",
            ["ToolLine"] = "Linea [2]",
            ["ToolRectangle"] = "Rettangolo [3]",
            ["ToolCircle"] = "Cerchio [4]",
            ["ToolArc"] = "Arco [5]",
            ["ToolText"] = "Testo [6]",
            ["ToolRuler"] = "Righello [7]",
            ["ToolEraser"] = "Gomma [8]",
            ["ToolColor"] = "Seleziona Colore",
            ["ToolFont"] = "Seleziona Font",
            ["ToolUndo"] = "Annulla (Ctrl+Z)",
            ["ToolRedo"] = "Ripristina (Ctrl+X / Ctrl+Y)",
            ["ToolGrid"] = "Attiva griglia (G)",
            ["StatusSize"] = "Dimensione",
            ["StatusBlocks"] = "Blocchi",
            ["StatusZoom"] = "Zoom",
            ["AboutTitle"] = "Informazioni su MCBlueprint",
            ["AboutText"] = "MCBlueprint — Strumento di architettura per Minecraft",
            ["BlocksLabel"] = "bl."
        },
        [Language.Korean] = new()
        {
            ["AppTitle"] = "MCBlueprint — 마인크래프트 건축 설계 도구",
            ["NewProjectTitle"] = "MCBlueprint — 새 프로젝트",
            ["MenuFile"] = "파일",
            ["MenuNew"] = "새 프로젝트",
            ["MenuOpen"] = "열기...",
            ["MenuSave"] = "저장",
            ["MenuSaveAs"] = "다른 이름으로 저장...",
            ["MenuExit"] = "종료",
            ["MenuEdit"] = "편집",
            ["MenuUndo"] = "실행 취소",
            ["MenuRedo"] = "다시 실행",
            ["MenuClearAll"] = "모두 지우기",
            ["MenuView"] = "보기",
            ["MenuGrid"] = "격자",
            ["MenuCenterCamera"] = "카메라 중앙 배치",
            ["MenuLanguage"] = "언어",
            ["MenuHelp"] = "도움말",
            ["MenuAbout"] = "정보",
            ["ToolPointer"] = "포인터 / 텍스트 이동 [0]",
            ["ToolBrush"] = "브러시 [1]",
            ["ToolLine"] = "직선 [2]",
            ["ToolRectangle"] = "직사각형 [3]",
            ["ToolCircle"] = "원 [4]",
            ["ToolArc"] = "호 [5]",
            ["ToolText"] = "텍스트 [6]",
            ["ToolRuler"] = "줄자 [7]",
            ["ToolEraser"] = "지우개 [8]",
            ["ToolColor"] = "색상 선택",
            ["ToolFont"] = "글꼴 선택",
            ["ToolUndo"] = "실행 취소 (Ctrl+Z)",
            ["ToolRedo"] = "다시 실행 (Ctrl+X / Ctrl+Y)",
            ["ToolGrid"] = "격자 토글 (G)",
            ["StatusSize"] = "크기",
            ["StatusBlocks"] = "블록 수",
            ["StatusZoom"] = "확대/축소",
            ["AboutTitle"] = "MCBlueprint 정보",
            ["AboutText"] = "MCBlueprint — 마인크래프트 2D 건축 설계 도구",
            ["BlocksLabel"] = "개"
        }
    };
}
